// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Mqttxn struct {
	BatchNumber                string           `json:"batch_number"`
	TransactionToken           string           `json:"transaction_token"`
	PostDate                   pgtype.Timestamp `json:"post_date"`
	InitiatingTransactionToken pgtype.Text      `json:"initiating_transaction_token"`
	ReferenceTransactionToken  pgtype.Text      `json:"reference_transaction_token"`
	ReversalTransactionToken   pgtype.Text      `json:"reversal_transaction_token"`
	ChargebackToken            pgtype.Text      `json:"chargeback_token"`
	TransactionStatus          string           `json:"transaction_status"`
	ActingUserToken            pgtype.UUID      `json:"acting_user_token"`
	ActingCardToken            pgtype.UUID      `json:"acting_card_token"`
	ActingCardLastFour         int32            `json:"acting_card_last_four"`
	Merchant                   string           `json:"merchant"`
	Network                    string           `json:"network"`
	MerchantCategoryCode       int32            `json:"merchant_category_code"`
	Currency                   string           `json:"currency"`
	Purchases                  pgtype.Numeric   `json:"purchases"`
	Returns                    pgtype.Numeric   `json:"returns"`
	Interchange                pgtype.Numeric   `json:"interchange"`
	PinDebitAssocFees          pgtype.Numeric   `json:"pin_debit_assoc_fees"`
	Chargebacks                pgtype.Numeric   `json:"chargebacks"`
	Basedataid                 pgtype.Int4      `json:"basedataid"`
}

type Vsstxn struct {
	Uuid            pgtype.UUID      `json:"uuid"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	Amount          pgtype.Numeric   `json:"amount"`
	Merchant        string           `json:"merchant"`
	SettlementDate  pgtype.Date      `json:"settlement_date"`
	PurchaseDate    pgtype.Timestamp `json:"purchase_date"`
	Currency        string           `json:"currency"`
	ApprovalNumber  int32            `json:"approval_number"`
	IntFee          pgtype.Numeric   `json:"int_fee"`
	MerchantCountry string           `json:"merchant_country"`
	Type            string           `json:"type"`
}
